name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
    paths:
      - '../../charts'

permissions:
  contents: read

jobs:
  lint-charts:
    name: Lint Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Set up helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint charts
        run: ct --config .github/ct.yaml lint --debug

      - name: Run unit tests
        run: |
          for chart in $(ct list-changed --config .github/ct-lint.yaml); do
            if [ -d "$chart/tests/" ]; then
              helm unittest $chart
            else
              echo "No unit tests found for $chart"
            fi
          done

      - name: Install Helm Docs
        run: |
          version="1.14.2"
          wget -O helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v${version}/helm-docs_${version}_Linux_x86_64.tar.gz
          tar --extract --verbose --file="helm-docs.tar.gz" helm-docs

      - name: Verify Helm docs are up to date
        run: |
          ./helm-docs
          git diff --exit-code -- ./charts/**

